version: "2"
services:
  db:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
  app:
    container_name: musix
    build: ./
    ports:
      - '8080:8080'
    links:
      - db:mongodb